sudo: 
  # required
  false

language: 
  c 

services:
  - docker

#addons:
#  apt:
#    packages:
#    - gfortran

before_install:
  # # update Docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

script:
  - pwd
